export { default as Button } from "./simple/Button";
export { default as Background } from "./simple/Background";
export { BackgroundLogged } from "./simple/Background";
export { default as BackButton } from "./simple/BackButton";
export { default as Header } from "./simple/Header";
export { default as Logo } from "./simple/Logo";
export { default as Paragraph } from "./simple/Paragraph";
export { default as TextInput } from "./simple/TextInput";
export { default as HorizontalSeparator } from "./simple/HorizontalSeparator";
export { default as FormHeader } from "./form/FormHeader";
export { default as ProvinCityFilter } from "./shared/ProvinCityFilter";
export { default as CustomChips } from "./shared/CustomChips";
//export { default as  } from "./";
